### ISSUE TITLE
运行 run_ner/seq.sh 无反应，并没有下载对应的 ./dataset

### ISSUE THREAD

**Issue by liwentao42** [zjunlp/OpenUE#23]
您好！非常感谢该项目的开放与维护。

我在尝试运行时出现了两个问题：

1. 在 windows 10 - 64 位 环境下使用 Pycharm，安装完依赖和其他文件后，运行 run_ner/seq 没有反应，并没有下载对应的 ./dataset以及生成目录。

2. 在 colab 中使用 OpenUE_demo.ipynb  进行训练后尝试在使用 srcripts下 的 interactive.sh 时，报错：

![image](https://user-images.githubusercontent.com/91654424/150680393-783e94e4-cf2e-41bd-ba3c-35ba15ecf778.png)

Using /usr/local/lib/python3.7/dist-packagesFinished processing dependencies for openue==0.2.501/23/2022 12:58:52 - INFO - openue.data.data_module -   add total special tokens: 50 
 ['[relation0]', '[relation1]', '[relation2]', '[relation3]', '[relation4]', '[relation5]', '[relation6]', '[relation7]', '[relation8]', '[relation9]', '[relation10]', '[relation11]', '[relation12]', '[relation13]', '[relation14]', '[relation15]', '[relation16]', '[relation17]', '[relation18]', '[relation19]', '[relation20]', '[relation21]', '[relation22]', '[relation23]', '[relation24]', '[relation25]', '[relation26]', '[relation27]', '[relation28]', '[relation29]', '[relation30]', '[relation31]', '[relation32]', '[relation33]', '[relation34]', '[relation35]', '[relation36]', '[relation37]', '[relation38]', '[relation39]', '[relation40]', '[relation41]', '[relation42]', '[relation43]', '[relation44]', '[relation45]', '[relation46]', '[relation47]', '[relation48]', '[relation49]']
Traceback (most recent call last):
  File "main.py", line 146, in <module>
    main()
  File "main.py", line 94, in main
    lit_model = litmodel_class(args=args, data_config=data.get_config())
  File "/usr/local/lib/python3.7/dist-packages/openue/lit_models/transformer.py", line 166, in __init__
    self._init_model()
  File "/usr/local/lib/python3.7/dist-packages/openue/lit_models/transformer.py", line 175, in _init_model
    self.model = Inference(self.args)
  File "/usr/local/lib/python3.7/dist-packages/openue/models/model.py", line 145, in __init__
    self._init_models()
  File "/usr/local/lib/python3.7/dist-packages/openue/models/model.py", line 174, in _init_models
    label2id={label: i for i, label in enumerate(self.labels_seq)},
  File "/usr/local/lib/python3.7/dist-packages/transformers/models/auto/configuration_auto.py", line 582, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/transformers/configuration_utils.py", line 556, in get_config_dict
    local_files_only=local_files_only,
  File "/usr/local/lib/python3.7/dist-packages/transformers/configuration_utils.py", line 844, in get_configuration_file
    path_or_repo, revision=revision, use_auth_token=use_auth_token, local_files_only=local_files_only
  File "/usr/local/lib/python3.7/dist-packages/transformers/file_utils.py", line 2103, in get_list_of_files
    return list_repo_files(path_or_repo, revision=revision, token=token)
  File "/usr/local/lib/python3.7/dist-packages/huggingface_hub/hf_api.py", line 885, in list_repo_files
    repo_id, revision=revision, token=token, timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/huggingface_hub/hf_api.py", line 868, in model_info
    r.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/output/ske/seq/epoch=2-Eval

3. 应该如何在训练完成后进行指定输入文本的知识图谱提取呢（以 Colab 上的 Demo 为例）？使用 lit_model.inference(inputs) 吗？

祝您有愉快的一天！
因我刚开始这方面的工作，多有叨扰，感激不尽。

**Comment by CheaSim** [comment]
你好，很荣幸你能使用我们开发的框架。 
* 请问使用的数据集是 `ske`吗，我使用命令测试了是可以成功下载该数据集合的。
* `interative.sh`报错应该是你需要修改已经训练好的两个模型路径，请确保是正确的路径。 主要每次训练保存的模型可能不太一样，需要手动调整。
* 如果进行知识图谱构建，可能还需要实体消歧的过程，我们这个框架主要处理的是文本三元组的抽取，使用inference即可从纯文本句子中抽取出，**预先定义好的**关系和对应的头尾实体。
