### ISSUE TITLE
run_seq.sh报错：Can't pickle local object 'get_linear_schedule_with_warmup.<locals>.lr_lambda'

### ISSUE THREAD

**Issue by 4thfever** [zjunlp/OpenUE#24]
Traceback (most recent call last):                                                                                  
  File "main.py", line 146, in <module>                                                       
    main()                                                                                                                    
  File "main.py", line 117, in main            
    if not test_only: trainer.fit(lit_model, datamodule=data)                         
  File "/cephfs/xqwang/openue/openue/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)                                                                   
  File "/cephfs/xqwang/openue/openue/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 756, in _run
    self.dispatch()                                                                               
  File "/cephfs/xqwang/openue/openue/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 797, in dispatch
    self.accelerator.start_training(self)                                                  
  File "/cephfs/xqwang/openue/openue/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)                                            
  File "/cephfs/xqwang/openue/openue/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 122, in start_training
    mp.spawn(self.new_process, **self.mp_spawn_kwargs)                                
  File "/cephfs/xqwang/openue/openue/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')              
  File "/cephfs/xqwang/openue/openue/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 179, in start_processes
    process.start()              
 File "/root/miniconda3/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)                                                                                     
  File "/root/miniconda3/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)                                                                                            
  File "/root/miniconda3/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)                                                                                            
  File "/root/miniconda3/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)                                                                                                              
  File "/root/miniconda3/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)                                                                                                                
  File "/root/miniconda3/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)                                                                        
AttributeError: Can't pickle local object 'get_linear_schedule_with_warmup.<locals>.lr_lambda'

请问这个是什么问题呢？run_ner.sh也遇到了同样的问题。依赖都是按照requirements安装的。

**Comment by CheaSim** [comment]
你好，请检查一下`pickle`的版本，我们开发环境的版本是`pickle==0.7.5`。
